### PR TITLE
Proper templating for advanced-cache.php's content

### PR DESCRIPTION
**Pull request by szepeviktor**
Actually windows line ends were in reverse order.

### CODE REVIEW

**Comment by tlovett1** [comment]
What's the motivation behind this?

**Comment by szepeviktor** [comment]
The plugin generates invalid line ends. The two bytes are in reverse order.
And if you concatenate strings with variables it cannot be read by humans.


-- 
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by tlovett1** [comment]
Can we do this without ruining the formatting of the code?

**Comment by szepeviktor** [comment]
What do you suggest?

**Comment by tlovett1** [comment]
Line endings were fixed in a different commit. Thanks!

**Pull request closed without merging**
